apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.15.1
    helm:
      releaseName: cert-manager
      values: |-
        crds:
          enabled: true
        extraObjects:
          - |
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: default-issuer
            spec:
              acme:
                server: https://acme-v02.api.letsencrypt.org/directory
                privateKeySecretRef:
                  name: letsencrypt-issuer-account-key
                solvers:
                - http01:
                    ingress:
                      ingressClassName: nginx
        ingressShim:
          defaultIssuerName: default-issuer
          defaultIssuerKind: ClusterIssuer
          defaultIssuerGroup: cert-manager.io
            
        webhook:
          validatingWebhookConfiguration:
            namespaceSelector:
              matchExpressions:
                - key: "cert-manager.io/disable-validation"
                  operator: "NotIn"
                  values:
                    - "true"
                - key: kubernetes.azure.com/managedby	
                  operator: NotIn	
                  values:	
                    - aks	
                - key: control-plane	
                  operator: NotIn	
                  values:	
                    - 'true'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager