apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: limited
  name: limited
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: limited
spec:
  hard:
    requests.cpu: "250m"
    requests.memory: 50Mi
    limits.memory: 500Mi

