apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.16.0
    helm:
      releaseName: crossplane
#      values: |-
#        configuration:
#          packages:
#          - xpkg.upbound.io/upbound/platform-ref-aws:v1.1.0
#          - xpkg.upbound.io/upbound/platform-ref-azure:v0.12.0
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system