apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 29.0.1
    helm:
      releaseName: traefik
      values: |-
        entryPoints:
          metrics:
            address: :8082
        experimental:
          kubernetesGateway:
            enabled: true
            namespacePolicy: All
        ingressClass:
          name: traefik
        logs:
          access:
            enabled: true
            fields:
              defaultMode: keep
              headers:
                defaultMode: keep
                names:
                  Authorization: drop
                  User-Agent: keep
              names:
                ClientUsername: keep
          general:
            level: DEBUG
        metrics:
          prometheus:
            addEntryPointsLabels: true
            addRoutersLabels: true
            addServicesLabels: true
            entryPoint: metrics
        podSecurityContext:
          fsGroup: 65532
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
        ports:
          web:
            redirectTo: 
              port: websecure
        service:
          spec:
            externalTrafficPolicy: Local
        extraObjects:
          - |
            apiVersion: cert-manager.io/v1
            kind: Certificate
            metadata:
              name: traefik-ingress-cert
              namespace: traefik
            spec:
              dnsNames:
              - traefik.osii.nneir-dev.pub.azure.novonordisk.com
              issuerRef:
                group: cert-manager.io
                kind: ClusterIssuer
                name: default-issuer
              secretName: traefik-ingress-cert
              usages:
              - digital signature
              - key encipherment
          - |
            apiVersion: traefik.io/v1alpha1
            kind: Middleware
            metadata:
              name: append-dashboard
              namespace: traefik
            spec:
              redirectRegex:
                regex: "^https:\\/\\/([^\\/]+)\\/?$"
                replacement: "https://$1/dashboard/"
          - |
            apiVersion: traefik.io/v1alpha1
            kind: IngressRoute
            metadata:
              name: dashboard
              namespace: traefik
            spec:
              entryPoints:
              - websecure
              routes:
              - kind: Rule
                match: "Host(`traefik.osii.nneir-dev.pub.azure.novonordisk.com`)"
                services:
                - kind: TraefikService
                  name: api@internal
                middlewares:
                - name: append-dashboard
                  namespace: traefik
              tls:
                secretName: traefik-ingress-cert
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik