apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secret
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: cco/externalsecrets/demo
      metadataPolicy: None
      property: hello
    secretKey: hello
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: demo-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: demo-secret
    template:
      data:
        hello: '{{ .hello }}'
      engineVersion: v2
      mergePolicy: Replace
