apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: demo-secret-store
spec:
  conditions:
  - namespaces:
    - osii-test
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: cluster-secret-store-sa
            namespace: cco-secrets
      region: eu-central-1
      service: SecretsManager
